### ISSUE TITLE
Fitbit Sense: Displays a "?" in the step count feature

### ISSUE THREAD

**Issue by rajivchandna** [anha1/fitbit-acidclock#5]
![Display error](https://user-images.githubusercontent.com/29808928/100298756-7a7c6400-2fc4-11eb-9c0f-4c4465b2081e.jpeg)

How can one fix this?

**Comment by anha1** [comment]
Hello @rajivchandna 
Thank you for reporting this! The symbol "↑" works fine on Versa 3/Sense simulator and I don't have a physical device to investigate it.
As a workaround, I submitted for a review a build where "^" is used instead of "↑".
While it is not published, you can disable "Show steps per current hour" in setting to temporary hide this block.

**Comment by anha1** [comment]
The "^" workaround has been published, my Versa 3 will be delivered in December, then I'll get it I'll try to find a working Unicode symbol or use a picture instead.

**Comment by rajivchandna** [comment]
Works! Thank you for this incredible watchface!
